name: amara-backup

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  amarabackup:
    runs-on: ubuntu-latest
    steps:
      - name: Save website
        uses: JamieMagee/wayback@v1.3.28
        with:
          url: https://amarahospital.com/
          saveErrors: false
          saveOutlinks: true
          saveScreenshot: true